VALID_PRIVATE_IPV4 = "192.168.1.1"
VALID_PRIVATE_IPV6 = "fe80::ecee:eeff:feee:eeee"
VALID_PUBLIC_IPV4 = "8.8.8.8"
VALID_PUBLIC_IPV6 = "2a00:1450:4009:815::200e"
INVALID_PUBLIC_IPV4 = "192.168.1.001"
INVALID_PUBLIC_IPV6 = "2a00:1450:4009:815::200efoo"
VALID_HOSTNAME = "google.com"
INVALID_HOSTNAME = "gooooooglee.com"
CONNECTABLE_PORT = 443
NOT_CONNECTABLE_PORT = 22
VALID_PORTS = [CONNECTABLE_PORT, NOT_CONNECTABLE_PORT]
INVALID_PORTS_MIX = VALID_PORTS + [9999999]
SOCKET_TIMEOUT = 1
SOCKET_ADDR_IPV4_CONNECTABLE = (VALID_PUBLIC_IPV4, CONNECTABLE_PORT)
SOCKET_ADDR_IPV4_NOT_CONNECTABLE = (VALID_PUBLIC_IPV4, NOT_CONNECTABLE_PORT)
SOCKET_ADDR_IPV6_CONNECTABLE = (VALID_PUBLIC_IPV6, CONNECTABLE_PORT)
SOCKET_ADDR_IPV6_NOT_CONNECTABLE = (VALID_PUBLIC_IPV6, NOT_CONNECTABLE_PORT)


# Error messages
INVALID_PORT_ERROR = r"Port\(s\) '.*' is not in a valid range of \(1-65535\)"
NOT_RESOLVE_ERROR = r"Hostname '.*' does not appear to resolve"
NOT_VALID_IP_ERROR = r"'.*' does not appear to be an IPv4 or IPv6 address"
NOT_PUBLIC_IP_ERROR = r"IPv.* address '.*' does not appear to be public"
